apiVersion: v1
kind: ConfigMap
metadata:
  name: curiositymonolith-configmap
  namespace: curiositymonolith
data:
  SPRING_DATASOURCE_HOST: "130.61.176.102"
  SPRING_DATASOURCE_PORT: "3306"
  SPRING_DATASOURCE_DBNAME: "curiositydb"